version: "3.9"

services:
  mysql:
    container_name: db-user
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  postgres_payments:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_DB=payments
      - POSTGRES_PASSWORD=fiap
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_DATABASE=items"
      - "MONGO_INITDB_ROOT_USERNAME=fiap"
      - "MONGO_INITDB_ROOT_PASSWORD=fiap"
    ports:
      - "27777:27017"
    volumes:
      - mongodb:/data/db

  postgres_cart:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_DB=cart
      - POSTGRES_PASSWORD=fiap
    ports:
      - "5433:5432"

volumes:
  mongodb:
    driver: local