version: "3.9"
services:
  postgres:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_DB=payments
      - POSTGRES_PASSWORD=fiap
    ports:
      - "5432:5432"