version: "3.9"

services:
  mysql:
    container_name: db-user
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"